// <auto-generated />
using System;
using Infrastructure.AI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations.AIObservationDb
{
    [DbContext(typeof(AIObservationDbContext))]
    partial class AIObservationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.AI.Models.ExerciseStats", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExerciseName")
                        .HasColumnType("text");

                    b.Property<decimal>("AverageWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalReps")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSets")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalVolume")
                        .HasColumnType("numeric");

                    b.HasKey("UserId", "ExerciseName");

                    b.ToTable("ExerciseStats", (string)null);
                });

            modelBuilder.Entity("Common.AI.Models.MuscleGroupStats", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("MuscleGroup")
                        .HasColumnType("text");

                    b.Property<decimal>("AverageIntensity")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalExercises")
                        .HasColumnType("integer");

                    b.Property<int>("TotalReps")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSets")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalVolume")
                        .HasColumnType("numeric");

                    b.HasKey("UserId", "MuscleGroup");

                    b.ToTable("MuscleGroupStats", (string)null);
                });

            modelBuilder.Entity("Common.AI.Observations.ExerciseAddedObservation", b =>
                {
                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderInWorkout")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("VolumeData")
                        .HasColumnType("numeric");

                    b.HasKey("WorkoutId", "Timestamp");

                    b.ToTable("ExerciseAddedObservations", (string)null);
                });

            modelBuilder.Entity("Common.AI.Observations.WorkoutCompletedObservation", b =>
                {
                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExerciseCount")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TotalDuration")
                        .HasColumnType("interval");

                    b.Property<decimal>("TotalVolume")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkoutId", "Timestamp");

                    b.ToTable("WorkoutCompletedObservations", (string)null);
                });

            modelBuilder.Entity("Common.AI.Observations.ExerciseAddedObservation", b =>
                {
                    b.OwnsOne("Common.AI.Observations.ExerciseDetails", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ExerciseAddedObservationWorkoutId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ExerciseAddedObservationTimestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal>("IntensityPercent1Rm")
                                .HasColumnType("numeric")
                                .HasColumnName("IntensityPercent1Rm");

                            b1.Property<string>("MuscleGroup")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MuscleGroup");

                            b1.Property<string>("Name")
                                .HasColumnType("text")
                                .HasColumnName("ExerciseName");

                            b1.HasKey("ExerciseAddedObservationWorkoutId", "ExerciseAddedObservationTimestamp");

                            b1.ToTable("ExerciseAddedObservations");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseAddedObservationWorkoutId", "ExerciseAddedObservationTimestamp");

                            b1.OwnsMany("Common.Workouts.SetInfo", "Sets", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<decimal>("Estimated1Rm")
                                        .HasColumnType("numeric");

                                    b2.Property<int>("Index")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Reps")
                                        .HasColumnType("integer");

                                    b2.Property<DateTime>("Timestamp")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<float>("Weight")
                                        .HasColumnType("real");

                                    b2.Property<Guid>("WorkoutId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("WorkoutId", "Timestamp");

                                    b2.ToTable("ExerciseAddedObservationSets", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("WorkoutId", "Timestamp");
                                });

                            b1.Navigation("Sets");
                        });

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
