// <auto-generated />
using System;
using Infrastructure.AI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.AIObservationDb
{
    [DbContext(typeof(AIObservationDbContext))]
    [Migration("20260317161635_AddSetIndexToExerciseSets")]
    partial class AddSetIndexToExerciseSets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Common.AI.Observations.ExerciseAddedObservation", b =>
                {
                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderInWorkout")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VolumeData")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkoutId", "Timestamp");

                    b.ToTable("ExerciseAddedObservations", (string)null);
                });

            modelBuilder.Entity("Common.AI.Observations.WorkoutCompletedObservation", b =>
                {
                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseCount")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TotalDuration")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalVolume")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkoutId", "Timestamp");

                    b.ToTable("WorkoutCompletedObservations", (string)null);
                });

            modelBuilder.Entity("Common.AI.Observations.ExerciseAddedObservation", b =>
                {
                    b.OwnsOne("Common.AI.Observations.ExerciseDetails", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ExerciseAddedObservationWorkoutId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("ExerciseAddedObservationTimestamp")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("IntensityPercent1Rm")
                                .HasColumnType("TEXT")
                                .HasColumnName("IntensityPercent1Rm");

                            b1.Property<string>("MuscleGroup")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("MuscleGroup");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT")
                                .HasColumnName("ExerciseName");

                            b1.HasKey("ExerciseAddedObservationWorkoutId", "ExerciseAddedObservationTimestamp");

                            b1.ToTable("ExerciseAddedObservations");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseAddedObservationWorkoutId", "ExerciseAddedObservationTimestamp");

                            b1.OwnsMany("Common.Workouts.SetInfo", "Sets", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<decimal>("Estimated1Rm")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Index")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Reps")
                                        .HasColumnType("INTEGER");

                                    b2.Property<DateTime>("Timestamp")
                                        .HasColumnType("TEXT");

                                    b2.Property<float>("Weight")
                                        .HasColumnType("REAL");

                                    b2.Property<Guid>("WorkoutId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("WorkoutId", "Timestamp");

                                    b2.ToTable("ExerciseAddedObservationSets", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("WorkoutId", "Timestamp");
                                });

                            b1.Navigation("Sets");
                        });

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
