// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(GymTrackerDbContext))]
    [Migration("20260423072835_AddExerciseDetailsColumns")]
    partial class AddExerciseDetailsColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Domain.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ExerciseId");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<float?>("Height")
                        .HasColumnType("REAL");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<float?>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Workouts.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("WorkoutId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts", (string)null);
                });

            modelBuilder.Entity("Domain.Workouts.Workout", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Domain.Workouts.ExercisePerformed", "Exercises", b1 =>
                        {
                            b1.Property<Guid>("ExercisePerformedId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ExerciseId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("WorkoutId")
                                .HasColumnType("TEXT");

                            b1.HasKey("ExercisePerformedId");

                            b1.HasIndex("ExerciseId");

                            b1.HasIndex("WorkoutId", "ExerciseId")
                                .IsUnique();

                            b1.ToTable("WorkoutExercises", (string)null);

                            b1.HasOne("Domain.Exercises.Exercise", null)
                                .WithMany()
                                .HasForeignKey("ExerciseId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("WorkoutId");

                            b1.OwnsMany("Domain.Workouts.SetRecord", "Sets", b2 =>
                                {
                                    b2.Property<Guid>("SetRecordId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal>("Estimated1Rm")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("ExercisePerformedId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Reps")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("SetIndex")
                                        .HasColumnType("INTEGER");

                                    b2.Property<float>("Weight")
                                        .HasColumnType("REAL");

                                    b2.HasKey("SetRecordId");

                                    b2.HasIndex("ExercisePerformedId", "SetIndex")
                                        .IsUnique();

                                    b2.ToTable("ExerciseSets", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ExercisePerformedId");
                                });

                            b1.Navigation("Sets");
                        });

                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
