$envFile = Join-Path $PSScriptRoot ".env"
$exampleCandidates = @()
$exampleCandidates += Join-Path $PSScriptRoot ".env.example"
$exampleCandidates += Join-Path (Join-Path $PSScriptRoot "..") "docs\.env.example"
$exampleCandidates += Join-Path (Join-Path $PSScriptRoot "..") ".env.example"
$exampleFile = $exampleCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1

if (-not (Test-Path $envFile)) {
    if (Test-Path $exampleFile) {
        Copy-Item $exampleFile $envFile
    } else {
        # Create a minimal .env for local development if no example exists
        @"
# Minimal .env generated by ensure-jwt-key.ps1
JWT__KEY=
JWT__ISSUER=GymTracker
JWT__AUDIENCE=GymTracker
FITNESS_AGENT__GITHUBTOKEN=ollama
FITNESS_AGENT__MODELID=qwen2.5:7b
FITNESS_AGENT__ENDPOINT=http://ollama:11434
"@ | Set-Content -Path $envFile -Encoding UTF8
    }
}

$content = Get-Content $envFile -Raw
if ($content -match '(?m)^JWT__KEY=\s*$' -or $content -notmatch '(?m)^JWT__KEY=.+$') {
    $secret = [Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Maximum 256 }))
    if ($content -match '(?m)^JWT__KEY=.*$') {
        $content = $content -replace '(?m)^JWT__KEY=.*$', "JWT__KEY=$secret"
    } else {
        $content = $content.TrimEnd() + "`r`nJWT__KEY=$secret`r`n"
    }

    Set-Content -Path $envFile -Value $content
    Write-Host "Generated JWT__KEY in $envFile"
} else {
    Write-Host "JWT__KEY already exists in $envFile"
}
